### PR TITLE
Graph multiple metrics

### PR DESCRIPTION
**Pull request by eugeniobaglieri**

### CODE REVIEW

**Comment by emartynov** [comment]
Guys, one observation - 267 files changed. I understand it is because we keep pods dependencies in the repository. But how I can find project files that are changed in this pull request?

**Comment by eugeniobaglieri** [comment]
Commit 549bb6c contains all pod updates.
how do you suggest to proceed?

**Comment by chwalters** [comment]
I am hoping to get it all merged this week.  Maybe in the future we can keep pod changes to separate commits to make it easier to see what project files have changed.  Any other suggestions welcome, and thanks again for the contributions

**Comment by emartynov** [comment]
The suggestion is to make pods update as separate merge requests. But it is up to you guys.

**Comment by chwalters** [comment]
Your suggestion regarding pod updates as separate merge request would be nice, I see that the framework changes were in their own commit now

**Comment by chwalters** [comment]
Closing the PR, had to merge by hand, please check develop branch

**Pull request closed without merging**
